# Generated by Django 4.1.2 on 2022-11-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmlandPinOriginals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farmland_pin_originals',
            },
        ),
    ]
